### ISSUE TITLE
Node Package failed to install

### ISSUE THREAD

**Issue by JasonBSteele** [otaviojr/node-red-contrib-smartthings#86]
I tried to update the node but it hasn't installed. I thought it might be because node need updating so I used nvm to install v16.17.1. 

However, it still does not install successfully. This is the log I get:
`
-----------------------------------------------------------
2022-10-11T20:11:04.594Z Install : node-red-contrib-smartthings 0.0.42

2022-10-11T20:11:00.639Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-smartthings@0.0.42
2022-10-11T20:11:47.905Z [err] npm
2022-10-11T20:11:47.906Z [err]  WARN deprecated messageformat@2.3.0: Package renamed as '@messageformat/core', see messageformat.github.io for more details. 'messageformat@4' will eventually provide a polyfill for Intl.MessageFormat, once it's been defined by Unicode & ECMA.
2022-10-11T20:12:11.436Z [out] 
2022-10-11T20:12:11.436Z [out] > usb@1.6.3 install /home/pi/.node-red/node_modules/usb
2022-10-11T20:12:11.436Z [out] > prebuild-install --verbose || node-gyp rebuild
2022-10-11T20:12:11.436Z [out] 
2022-10-11T20:12:12.490Z [err] prebuild-install
2022-10-11T20:12:12.493Z [err]  
2022-10-11T20:12:12.493Z [err] info begin Prebuild-install version 5.3.4
2022-10-11T20:12:12.508Z [err] prebuild-install
2022-10-11T20:12:12.508Z [err]  info looking for cached prebuild @ /home/pi/.npm/_prebuilds/470134-usb-v1.6.3-node-v72-linux-arm.tar.gz
2022-10-11T20:12:12.510Z [err] prebuild-install
2022-10-11T20:12:12.512Z [err]  http request GET https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v72-linux-arm.tar.gz
2022-10-11T20:12:13.172Z [err] prebuild-install
2022-10-11T20:12:13.174Z [err]  http 404 https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v72-linux-arm.tar.gz
2022-10-11T20:12:13.185Z [err] prebuild-install
2022-10-11T20:12:13.187Z [err]  WARN install No prebuilt binaries found (target=12.18.0 runtime=node arch=arm libc= platform=linux)
2022-10-11T20:12:15.748Z [out] make: Entering directory '/home/pi/.node-red/node_modules/usb/build'
2022-10-11T20:12:15.751Z [out]   CC(target) Release/obj.target/libusb/libusb/libusb/core.o
2022-10-11T20:12:17.538Z [out]   CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
2022-10-11T20:12:19.020Z [out]   CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
2022-10-11T20:12:19.524Z [out]   CC(target) Release/obj.target/libusb/libusb/libusb/io.o
2022-10-11T20:12:21.211Z [out]   CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
2022-10-11T20:12:21.522Z [out]   CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
2022-10-11T20:12:21.978Z [out]   CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
2022-10-11T20:12:22.253Z [out]   CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
2022-10-11T20:12:22.483Z [out]   CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
2022-10-11T20:12:25.868Z [out]   CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
2022-10-11T20:12:26.054Z [err] ../libusb/libusb/os/linux_udev.c:40:10: fatal error: libudev.h: No such file or directory
2022-10-11T20:12:26.054Z [err]  #include <libudev.h>
2022-10-11T20:12:26.054Z [err]           ^~~~~~~~~~~
2022-10-11T20:12:26.054Z [err] compilation terminated.
2022-10-11T20:12:26.093Z [err] make: *** [libusb.target.mk:148: Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
2022-10-11T20:12:26.094Z [out] make: Leaving directory '/home/pi/.node-red/node_modules/usb/build'
2022-10-11T20:12:26.103Z [err] gyp ERR! build error 
2022-10-11T20:12:26.104Z [err] gyp ERR! stack Error: `make` failed with exit code: 2
2022-10-11T20:12:26.104Z [err] gyp ERR!
2022-10-11T20:12:26.105Z [err]  stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
2022-10-11T20:12:26.105Z [err] gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
2022-10-11T20:12:26.105Z [err] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
2022-10-11T20:12:26.107Z [err] gyp
2022-10-11T20:12:26.108Z [err]  ERR! System Linux 4.19.75-v7+
2022-10-11T20:12:26.108Z [err] gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2022-10-11T20:12:26.108Z [err] gyp 
2022-10-11T20:12:26.112Z [err] ERR! cwd /home/pi/.node-red/node_modules/usb
2022-10-11T20:12:26.112Z [err] gyp ERR! node -v v12.18.0
2022-10-11T20:12:26.112Z [err] gyp ERR! node-gyp -v v5.1.0
2022-10-11T20:12:26.112Z [err] gyp ERR! not ok 
2022-10-11T20:12:36.597Z [err] npm
2022-10-11T20:12:36.598Z [err]  WARN notsup Unsupported engine for @smartthings/core-sdk@5.1.2: wanted: {"node":">=14"} (current: {"node":"12.18.0","npm":"6.14.4"})
2022-10-11T20:12:36.598Z [err] npm WARN notsup Not compatible with your version of node/npm: @smartthings/core-sdk@5.1.2
2022-10-11T20:12:36.599Z [err] npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
2022-10-11T20:12:36.599Z [err] npm WARN node-red-project@0.0.1 No repository field.
2022-10-11T20:12:36.599Z [err] npm WARN node-red-project@0.0.1 No license field.
2022-10-11T20:12:36.603Z [err] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/zigbee-herdsman-converters/node_modules/fsevents):
2022-10-11T20:12:36.603Z [err] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
2022-10-11T20:12:36.603Z [err] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/zigbee-herdsman/node_modules/jest-haste-map/node_modules/fsevents):
2022-10-11T20:12:36.603Z [err] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
2022-10-11T20:12:36.603Z [err] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/zigbee-herdsman/node_modules/fsevents):
2022-10-11T20:12:36.603Z [err] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
2022-10-11T20:12:36.603Z [err] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.3 (node_modules/usb):
2022-10-11T20:12:36.603Z [err] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.3 install: 'prebuild-install --verbose || node-gyp rebuild'
2022-10-11T20:12:36.603Z [err] npm 
2022-10-11T20:12:36.615Z [err] WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
2022-10-11T20:12:36.615Z [err] 
2022-10-11T20:12:36.618Z [out] + node-red-contrib-smartthings@0.0.42
2022-10-11T20:12:36.618Z [out] updated 1 package in 93.734s
`

**Comment by JasonBSteele** [comment]
I needed to update Node Red as well.
